export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

//FAMILY
export const CREATE_FAMILY = 'CREATE_FAMILY';
export const FETCH_FAMILIES = 'FETCH_FAMILIES';
export const UPDATE_FAMILY = 'UPDATE_FAMILY';
export const DELETE_FAMILY = 'DELETE_FAMILY';
export  const START_LOADING = "START_LOADING";
export  const END_LOADING = "END_LOADING";

//CHILDREN
export const CREATE_CHILDREN = 'CREATE_CHILDREN';
export const FETCH_CHILDREN = 'FETCH_CHILDRENS';
export const FETCH_CHILDRENS = 'FETCH_CHILDRENS';
export const UPDATE_CHILDREN = 'UPDATE_CHILDREN';
export const DELETE_CHILDREN = 'DELETE_CHILDREN';
